Add counts of missing deps
rpm-software-management/dnf-plugins-core pull request #449
Opened 2022-01-07 16:47 UTC by jcpunk

For reviewing repoclosure results, it is handy to have raw counts sometimes.  Incremental fixes are easier to identify when you can see the numbers going down.

2022-01-10 07:39 UTC, kontura requested changes
Could you add a changelog message into the commit (as we have described in the README)?

Perhaps something like:
```
= changelog =
msg: [repoclosure] Print counts of missing dependencies
type: enhancement
```

2022-01-10 07:39 UTC, kontura commented on tests/test_repoclosure.py
>                              "  unresolved deps:",
The tests are still failing, you have to also add the `(1)` here.
`"  unresolved deps (1):",`

2022-01-10 07:39 UTC, kontura commented on tests/test_repoclosure.py
>                              "  unresolved deps:",
Here as well:
`" unresolved deps (1):",`

2022-01-10 07:39 UTC, kontura commented on tests/test_repoclosure.py
>                              "  unresolved deps:",
Here as well:
`" unresolved deps (1):",`

2022-01-10 17:29 UTC, jcpunk commented
I think I'm closer....

2022-01-11 07:43 UTC, kontura approved these changes

2022-01-11 07:44 UTC, merged