fix(repomanage): old option outputs the latest package.
rpm-software-management/dnf-plugins-core pull request #452
Opened 2022-03-30 06:17 UTC by mmatsuya

dnf repomanage --old option can output the latest package. 

One stream can have multiple versions. In the current logic for --old option, it consolidates all packages in the older versions.
But, the package version isn't always changed between the stream versions. If the older version has the same package version as ones in the newer stream versions, it output the latest versions.

A use case for this option was to remove the output older package from the repository. But, some latest packages are also removed, since the latest package also is output with --old option.

As an example, all xsom packages (including the latest one) in the pki-deps:10.6 stream are output with the --old option.

# dnf module info pki-deps |grep -e Version -e xsom
Version          : 8000020190524054914
                 : xsom-0:0-19.20110809svn.module+el8.0.0+3248+9d514f3b.noarch
                 : xsom-0:0-19.20110809svn.module+el8.0.0+3248+9d514f3b.src
Version          : 8000020190807021343
                 : xsom-0:0-19.20110809svn.module+el8.0.0+3892+c903d3f0.noarch
                 : xsom-0:0-19.20110809svn.module+el8.0.0+3892+c903d3f0.src
Version          : 8010020190731203900
                 : xsom-0:0-19.20110809svn.module+el8.1.0+3366+6dfb954c.noarch
                 : xsom-0:0-19.20110809svn.module+el8.1.0+3366+6dfb954c.src
Version          : 8020020191204213056
                 : xsom-0:0-19.20110809svn.module+el8.1.0+3366+6dfb954c.noarch
                 : xsom-0:0-19.20110809svn.module+el8.1.0+3366+6dfb954c.src
Version          : 8030020200527165326
                 : xsom-0:0-19.20110809svn.module+el8.1.0+3366+6dfb954c.noarch
                 : xsom-0:0-19.20110809svn.module+el8.1.0+3366+6dfb954c.src
Version          : 8040020201130152515
                 : xsom-0:0-19.20110809svn.module+el8.1.0+3366+6dfb954c.noarch
                 : xsom-0:0-19.20110809svn.module+el8.1.0+3366+6dfb954c.src
Version          : 8050020210611200146
                 : xsom-0:0-19.20110809svn.module+el8.1.0+3366+6dfb954c.noarch
                 : xsom-0:0-19.20110809svn.module+el8.1.0+3366+6dfb954c.src
Version          : 820190223041344
                 : xsom-0:0-19.20110809svn.module+el8+2468+c564cec5.noarch
                 : xsom-javadoc-0:0-19.20110809svn.module+el8+2468+c564cec5.noarch

# ls
Packages  repodata
# ls Packages/ |grep xsom
xsom-0-19.20110809svn.module+el8.0.0+3248+9d514f3b.noarch.rpm
xsom-0-19.20110809svn.module+el8.0.0+3892+c903d3f0.noarch.rpm
xsom-0-19.20110809svn.module+el8.1.0+3366+6dfb954c.noarch.rpm
xsom-0-19.20110809svn.module+el8+2468+c564cec5.noarch.rpm

# dnf repomanage --old . |grep xsom
./Packages/xsom-0-19.20110809svn.module+el8+2468+c564cec5.noarch.rpm
./Packages/xsom-0-19.20110809svn.module+el8.0.0+3248+9d514f3b.noarch.rpm
./Packages/xsom-0-19.20110809svn.module+el8.0.0+3892+c903d3f0.noarch.rpm
./Packages/xsom-javadoc-0-19.20110809svn.module+el8+2468+c564cec5.noarch.rpm

My proposal here is to check if each package in older stream is in the newer stream.

2022-04-11 10:31 UTC, kontura requested changes
Hello, thank you for the PR.

As discussed in RhBug: 2058676 could you please add this behavior as a separate option, document it and describe in the docs what are the differences to current `--old`?


Also can you add a changelog entry to the commit such as:
```
= changelog =
msg:         Add a new option --not-new to repomanage, it prints only rpms that are not new (resolves a use case when one rpm is both in new and old versions of a stream and therefore was printed in both cases).
type:        enhancement
resolves:    https://bugzilla.redhat.com/show_bug.cgi?id=2034736, https://bugzilla.redhat.com/show_bug.cgi?id=2058676
```
(As we describe in the README.)

2022-04-11 10:55 UTC, kontura commented
I have also create a CI test that we can use for this once its merged: https://github.com/rpm-software-management/ci-dnf-stack/pull/1084

2022-04-12 10:14 UTC, mmatsuya commented
Hi, Thanks for your review and comment.

I implemented a new option --oldonly (-O). This option does the same thing as --old, but it excludes the latest package.
Please let me know if there is anything I should fix in it. If the better option name exists, I will change into that.

2022-04-13 06:06 UTC, kontura requested changes
The code looks fine.

Could you add a description of the new option into https://github.com/rpm-software-management/dnf-plugins-core/blob/master/doc/repomanage.rst? 

Also could you clean up the git commit history? I think just one commit would be fine here (With some descriptive title and the `= changelog =..` section in its body.)

2022-04-13 09:30 UTC, closed without merging

2022-04-13 09:52 UTC, mmatsuya commented
Hi, another PR was created with just one commit and a change for repomanage.rst.
https://github.com/rpm-software-management/dnf-plugins-core/pull/453