pre-transaction-actions plugin implementation
rpm-software-management/dnf-plugins-core pull request #511
Opened 2023-11-29 09:55 UTC by mskrgulja

This is DNF implementation of pre-transactions-actions (originally for YUM.)
For creating it I used post-transaction-actions plugin as a starting point, so in essence this is very similar to post-transaction-actions, but with different hook and action names.

2023-11-29 09:55 UTC, pep8speaks commented
Hello @mskrgulja! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`plugins/pre-transaction-actions.py`](https://github.com/rpm-software-management/dnf-plugins-core/blob/1a1e0a4c43e6cd8333d89406667b0e7555a2477e/plugins/pre-transaction-actions.py):

> [Line 1:50](https://github.com/rpm-software-management/dnf-plugins-core/blob/1a1e0a4c43e6cd8333d89406667b0e7555a2477e/plugins/pre-transaction-actions.py#L1): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 4:121](https://github.com/rpm-software-management/dnf-plugins-core/blob/1a1e0a4c43e6cd8333d89406667b0e7555a2477e/plugins/pre-transaction-actions.py#L4): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (138 > 120 characters)
> [Line 24:1](https://github.com/rpm-software-management/dnf-plugins-core/blob/1a1e0a4c43e6cd8333d89406667b0e7555a2477e/plugins/pre-transaction-actions.py#L24): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2023-12-22 10:42 UTC, mskrgulja commented
Any news here :-)

2024-01-08 08:47 UTC, jrohel requested changes
Thank you for your PR.

Please:
- Replace "install", "update" and "remove" with "in" and "out".
- Merge "Corrected PEP 8 issues", "Fixed more PEP 8 issues", "Resolving build issues" commits with the first one. So only two commits remain - "Added the pre-transaction-actions plugin" and "Added myself to Authors file"
- Fix your "git" settings (or create commits under the correct user account). Make your commits contain the github name "mskrgulja" and not "root".
- Remove execute "x" right on "pre-transaction-actions.py" file.

2024-01-08 08:47 UTC, jrohel commented on doc/pre-transaction-actions.rst
> +   * ``install`` - packages that will be instaled on the system (install)
As I wrote in the review of the source code. Replace "install", "update" and "remove" with "in" and "out".

Based on the description of the "post-transaction-actions" plugin something like this:
   * ``in`` - packages that will appear on the system (downgrade, install, obsolete, reinstall, upgrade)
   * ``out`` - packages that will disappear from the system (downgraded, obsoleted, remove, upgraded)

2024-01-24 10:32 UTC, jrohel commented
@mskrgulja Thank you for the changes in the code.
I guess I confused you with the term "merge". I wanted something like git "fixup". To clear the history and leave only 2 commits  - "Added the pre-transaction-actions plugin" and "Added myself to Authors file"

2024-01-24 11:18 UTC, mskrgulja commented
> @mskrgulja Thank you for the changes in the code. I guess I confused you with the term "merge". I wanted something like git "fixup". To clear the history and leave only 2 commits - "Added the pre-transaction-actions plugin" and "Added myself to Authors file"

You are welcome.
Yes, I was little bit confused (my first time working with Github), but thanks for the clarification.
I will get some time in the next days to solve this.

Take care

2024-02-17 14:27 UTC, closed without merging

2024-02-17 14:27 UTC, mskrgulja commented
I don't know how to "fixup" all the commits so I'm closing this pull request and I will create another